# Generated by Django 5.0.1 on 2024-02-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('online_order', models.BooleanField(default=False)),
                ('book_table', models.BooleanField(default=False)),
                ('rate', models.FloatField()),
                ('votes', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('rest_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dish_liked', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cuisines', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
