# Generated by Django 5.0.1 on 2024-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
